services:
  - type: web
    name: volksw-backend
    env: python
    region: oregon
    plan: free
    rootDir: project/backend
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.7
      - key: HOST
        value: 0.0.0.0
    healthCheckPath: /health
    autoDeploy: true

